### ISSUE TITLE
problem at install

### ISSUE THREAD

**Issue by frigaut** [ANR-COMPASS/shesha#30]
Hey guys; following Damien's advice we are entering the issue here.
Trying to install compass on a machine with centos 7.6. Followed to the letter the installation guide in https://anr-compass.github.io/compass/install.html but I have an error when I run the tests:

## distro:
```bash
mutant:~/shesha/shesha/tests $ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
```

## error:
```bash
mutant:~/shesha/shesha/tests $ ./checkCompass.sh
[1/21] running test_pyr3_maskedpix
[2/21] running test_pyr_base
[3/21] running test_pyr_ELTpup
[4/21] running test_sh_base
[5/21] running test_sh_bpcog
[6/21] running test_sh_control_klbasis
[7/21] running test_sh_cured
[8/21] running test_sh_ELTpup
[9/21] running test_sh_generic
[10/21] running test_sh_geo
[11/21] running test_sh_influBessel
[12/21] running test_sh_influBlacknutt
[13/21] running test_sh_influGaussian
[14/21] running test_sh_influRadialSchwartz
[15/21] running test_sh_influSquareSchwartz
[16/21] running test_sh_kl
[17/21] running test_sh_lgs_corr
[18/21] running test_sh_lgs_wcog
[19/21] running test_sh_modopti
[20/21] running test_sh_mv
[21/21] running test_sh_tcog
Traceback (most recent call last):
  File "/home/frigaut/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/frigaut/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frigaut/shesha/shesha/tests/check.py", line 26, in <module>
    df = pandas.read_hdf("check.h5")
  File "/home/frigaut/miniconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 389, in read_hdf
    return store.select(key, auto_close=auto_close, **kwargs)
  File "/home/frigaut/miniconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 740, in select
    return it.get_result()
  File "/home/frigaut/miniconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 1518, in get_result
    results = self.func(self.start, self.stop, where)
  File "/home/frigaut/miniconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 733, in func
    columns=columns)
  File "/home/frigaut/miniconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 2995, in read
    start=_start, stop=_stop)
  File "/home/frigaut/miniconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 2540, in read_array
    ret = node[0][start:stop]
  File "/home/frigaut/miniconda3/lib/python3.7/site-packages/tables/vlarray.py", line 681, in __getitem__
    return self.read(start, stop, step)[0]
  File "/home/frigaut/miniconda3/lib/python3.7/site-packages/tables/vlarray.py", line 821, in read
    listarr = self._read_array(start, stop, step)
  File "tables/hdf5extension.pyx", line 2155, in tables.hdf5extension.VLArray._read_array
ValueError: cannot set WRITEABLE flag to True of this array
mutant:~/shesha/shesha/tests $
```

Is it related to hdf5? Perhaps the wrong version from the OS?

```bash
mutant:~/shesha/shesha/tests $ yum info hdf
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.serversaustralia.com.au
 * epel: mirror.aarnet.edu.au
 * extras: centos.mirror.serversaustralia.com.au
 * updates: mirror.optus.net
Available Packages
Name        : hdf
Arch        : x86_64
Version     : 4.2.13
Release     : 1.el7
Size        : 1.4 M
Repo        : epel/x86_64
Summary     : A general purpose library and file format for storing scientific
            : data
URL         : http://hdfgroup.org/products/hdf4/index.html
License     : BSD
Description : HDF is a general purpose library and file format for storing
            : scientific data. HDF can store two primary objects: datasets and
            : groups. A dataset is essentially a multidimensional array of data
            : elements, and a group is a structure for organizing objects in an
            : HDF file. Using these two basic objects, one can create and store
            : almost any kind of scientific data structure, such as images,
            : arrays of vectors, and structured and unstructured grids. You can
            : also mix and match them in HDF files according to your needs.

mutant:~/shesha/shesha/tests $
```

Thanks for any pointer (sinon je demande a Damien demain :-)

**Comment by frigaut** [comment]
Thanks. Closing.
